# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for A.T.L.A.S. Build with:  pyinstaller atlas.spec
#
# Notes that matter:
# - ONEDIR (not onefile): dist/ATLAS/ATLAS.exe + its dependencies in a folder.
#   Chosen over onefile because it triggers fewer antivirus false positives and
#   starts faster (no per-launch unpack to %TEMP%); the Inno installer wraps the
#   whole folder anyway.
# - Windowed by default (console=False → no console window). Set the env var
#   ATLAS_DEBUG_CONSOLE=1 before building to get a console build that prints
#   tracebacks — used to diagnose silent failures, then rebuild windowed.
# - Plugins are loaded FROM DISK at runtime, so PyInstaller's import tracer
#   never sees their dependencies — every library a built-in plugin lazily
#   imports must be listed in hiddenimports below, or the frozen build will
#   raise ImportError the first time that plugin runs.
# - plugins/, skills/, web/, wake/, assets/ are bundled as data; on first run
#   config.ensure_user_files() copies plugins/skills into %APPDATA%\ATLAS.

import os

block_cipher = None
DEBUG_CONSOLE = os.environ.get("ATLAS_DEBUG_CONSOLE") == "1"

a = Analysis(
    ["src/main.py"],
    pathex=["src"],
    binaries=[],
    # web/ ships the FUI; wake/ ships the wake-word docs (and atlas.onnx once
    # trained). Heavy voice/ONNX models are NOT bundled — they download to
    # models/ on first run (see core/models.py) to keep the exe small.
    datas=[("plugins", "plugins"), ("skills", "skills"),
           ("src/ui/web", "ui/web"), ("wake", "wake"), ("assets", "assets")],
    hiddenimports=[
        # lazily imported by core/ui at runtime
        "requests", "edge_tts", "pystray", "pystray._win32", "webview",
        # voice pipeline (lazy)
        "onnxruntime", "openwakeword", "openwakeword.model", "faster_whisper",
        "numpy",
        # lazily imported by plugins loaded from disk
        "keyboard", "pygetwindow", "pydirectinput", "sounddevice",
        "PIL.ImageGrab", "PIL.Image", "PIL.ImageDraw",
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        "unittest", "pydoc", "doctest", "test",
        "matplotlib", "scipy",                    # never ours; block accidental pulls
        "PIL.ImageTk", "PIL.ImageQt", "PIL.ImageShow",
        "setuptools", "pip", "wheel",
        "xmlrpc", "curses", "lib2to3",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ONEDIR: EXE holds only the launcher; COLLECT gathers the runtime folder.
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,     # onedir: binaries go to COLLECT, not the exe
    name="ATLAS",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,                  # harmless if UPX absent; ~30% smaller if present
    upx_exclude=["vcruntime140.dll", "python3*.dll"],
    console=DEBUG_CONSOLE,      # False = no console window (windowed default)
    disable_windowed_traceback=False,
    icon="assets/atlas.ico",   # generated by build.py from icon.png
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=["vcruntime140.dll", "python3*.dll"],
    name="ATLAS",              # → dist/ATLAS/ (contains ATLAS.exe)
)
